version: '3'

services:
  # nginx
  nginx:
    container_name: nginix-http-server
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /html:/usr/share/nginx/html